
GET http://localhost:4005/validate/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjI3MzFiZWQ5Yzc0OTFlMGVmMDNmODUyIiwiaWF0IjoxNjUxNzEwOTU3fQ.95Z4ZbwzIbTwrr7dbhoY0LEBoZNLVtS1KsFMCPZKOTk HTTP/1.1

#####

GET http://localhost:4001/menu/posts/allpost HTTP/1.1

#####

GET http://localhost:4005/login/cookie/6274163bab10eda43cce74dd HTTP/1.1
Content-Type: application/json

#####

GET http://localhost:4001/menu/audio/627a823846f2f2d3837e2ec4 HTTP/1.1

#####

PUT http://localhost:4001/menu/comment/627af1ecb85560ee3d04af82 HTTP/1.1
Content-Type: application/json

{
    "commentsid": "ahorasi"
}