
GET http://localhost:3077/menu/profile HTTP/1.1

#####


POST http://localhost:3077/menu/profile HTTP/1.1
Content-Type: application/json

{
    "username": "Joan",
    "password": "secretito",
    "mail": "joan@gmail.com"
}